[profile.release]
lto = true

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# See https://github.com/rust-lang/rust/issues/59302
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static"
]

# Same as above
[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static"
]
